environment:
  TEST_APP_ID: ENCRYPTED[!9f287ddc756b7c12b282fa965f66f0c957b193154a0e08436eef3befb926b91355c86f28938fd836977fdee4a336ccce!]
  # The flutter sdk is located in /Users/admin/flutter by default in cirrus cis
  MACOS_HOST_FLUTTER_SDK_DIR: /Users/admin/flutter

default_filters: &default_filters
  only_if: $CIRRUS_REPO_OWNER == 'AgoraIO-Extensions' && $CIRRUS_PR != '' && $CIRRUS_PR_LABELS !=~ '.*ci:skip.*'

default_macos_container: &default_macos_container
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14

android_build_task:
  <<: *default_filters
  <<: *default_macos_container

  matrix:
    - name: FLUTTER_VERSION 3.7.0
      env:
        FLUTTER_VERSION: 3.7.0
  switch_flutter_version_script:
    - cd ${MACOS_HOST_FLUTTER_SDK_DIR}
    - git fetch
    - git checkout ${FLUTTER_VERSION} && flutter precache

    matrix:
    - name: Build android on macos arm
      build_android_arm64_script:
        - cd example
        - flutter doctor -v
        - flutter packages get
        - flutter build apk

    - name: Build ios on macos arm
      build_android_arm64_script:
        - cd example
        - flutter doctor -v
        - flutter clean
        - flutter packages get
        - flutter build ios --no-codesign