name: 'NativeIrisApiRtmEngineBinding'
description: 'Bindings to IrisApiRtmEngine'

output: 'lib/src/bindings/native_iris_api_rtm_engine_bindings.dart'

headers:
  entry-points:
    - 'third_party/rtm/iris_rtm_c_api.h'
    
  include-directives:
    - 'third_party/rtm/iris_rtm_c_api.h'

llvm-path:
  - '/usr/local/opt/llvm'

# Generating typedefs need set the sdk constraints to >=2.14, remove it 
# if we can set our sdk constraints to >=2.14
typedefs:
  exclude:
    - 'Dart_Port'

functions:
  symbol-address:
    include:
      - 'OnEvent' # Match function name.