// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to IrisApiRtmEngine
class NativeIrisApiRtmEngineBinding {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeIrisApiRtmEngineBinding(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeIrisApiRtmEngineBinding.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.Int> _kBasicResultLength =
      _lookup<ffi.Int>('kBasicResultLength');

  int get kBasicResultLength => _kBasicResultLength.value;

  set kBasicResultLength(int value) => _kBasicResultLength.value = value;

  late final ffi.Pointer<ffi.Int> _kEventResultLenght =
      _lookup<ffi.Int>('kEventResultLenght');

  int get kEventResultLenght => _kEventResultLenght.value;

  set kEventResultLenght(int value) => _kEventResultLenght.value = value;

  late final ffi.Pointer<ffi.Int> _kBasicStringLength =
      _lookup<ffi.Int>('kBasicStringLength');

  int get kBasicStringLength => _kBasicStringLength.value;

  set kBasicStringLength(int value) => _kBasicStringLength.value = value;

  void enableUseJsonArray(
    int enable,
  ) {
    return _enableUseJsonArray(
      enable,
    );
  }

  late final _enableUseJsonArrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'enableUseJsonArray');
  late final _enableUseJsonArray =
      _enableUseJsonArrayPtr.asFunction<void Function(int)>();

  IrisApiRtmEnginePtr CreateIrisRtmEngine(
    ffi.Pointer<ffi.Void> engine,
  ) {
    return _CreateIrisRtmEngine(
      engine,
    );
  }

  late final _CreateIrisRtmEnginePtr = _lookup<
      ffi.NativeFunction<
          IrisApiRtmEnginePtr Function(
              ffi.Pointer<ffi.Void>)>>('CreateIrisRtmEngine');
  late final _CreateIrisRtmEngine = _CreateIrisRtmEnginePtr.asFunction<
      IrisApiRtmEnginePtr Function(ffi.Pointer<ffi.Void>)>();

  void DestroyIrisRtmEngine(
    IrisApiRtmEnginePtr engine,
  ) {
    return _DestroyIrisRtmEngine(
      engine,
    );
  }

  late final _DestroyIrisRtmEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(IrisApiRtmEnginePtr)>>(
          'DestroyIrisRtmEngine');
  late final _DestroyIrisRtmEngine =
      _DestroyIrisRtmEnginePtr.asFunction<void Function(IrisApiRtmEnginePtr)>();

  int CallIrisRtmApi(
    IrisApiRtmEnginePtr engine_ptr,
    ffi.Pointer<ApiParam> param,
  ) {
    return _CallIrisRtmApi(
      engine_ptr,
      param,
    );
  }

  late final _CallIrisRtmApiPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              IrisApiRtmEnginePtr, ffi.Pointer<ApiParam>)>>('CallIrisRtmApi');
  late final _CallIrisRtmApi = _CallIrisRtmApiPtr.asFunction<
      int Function(IrisApiRtmEnginePtr, ffi.Pointer<ApiParam>)>();

  IrisEventHandlerHandle CreateIrisEventHandler(
    ffi.Pointer<IrisCEventHandler> event_handler,
  ) {
    return _CreateIrisEventHandler(
      event_handler,
    );
  }

  late final _CreateIrisEventHandlerPtr = _lookup<
      ffi.NativeFunction<
          IrisEventHandlerHandle Function(
              ffi.Pointer<IrisCEventHandler>)>>('CreateIrisEventHandler');
  late final _CreateIrisEventHandler = _CreateIrisEventHandlerPtr.asFunction<
      IrisEventHandlerHandle Function(ffi.Pointer<IrisCEventHandler>)>();

  void DestroyIrisEventHandler(
    IrisEventHandlerHandle handler,
  ) {
    return _DestroyIrisEventHandler(
      handler,
    );
  }

  late final _DestroyIrisEventHandlerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(IrisEventHandlerHandle)>>(
          'DestroyIrisEventHandler');
  late final _DestroyIrisEventHandler = _DestroyIrisEventHandlerPtr.asFunction<
      void Function(IrisEventHandlerHandle)>();
}

abstract class IrisAppType {
  static const int kAppTypeNative = 0;
  static const int kAppTypeCocos = 1;
  static const int kAppTypeUnity = 2;
  static const int kAppTypeElectron = 3;
  static const int kAppTypeFlutter = 4;
  static const int kAppTypeUnreal = 5;
  static const int kAppTypeXamarin = 6;
  static const int kAppTypeApiCloud = 7;
  static const int kAppTypeReactNative = 8;
  static const int kAppTypePython = 9;
  static const int kAppTypeCocosCreator = 10;
  static const int kAppTypeRust = 11;
  static const int kAppTypeCSharp = 12;
  static const int kAppTypeCef = 13;
  static const int kAppTypeUniApp = 14;
}

abstract class IrisLogLevel {
  static const int levelTrace = 0;
  static const int levelDebug = 1;
  static const int levelInfo = 2;
  static const int levelWarn = 3;
  static const int levelErr = 4;
}

class EventParam extends ffi.Struct {
  external ffi.Pointer<ffi.Char> event;

  external ffi.Pointer<ffi.Char> data;

  @ffi.UnsignedInt()
  external int data_size;

  external ffi.Pointer<ffi.Char> result;

  external ffi.Pointer<ffi.Pointer<ffi.Void>> buffer;

  external ffi.Pointer<ffi.UnsignedInt> length;

  @ffi.UnsignedInt()
  external int buffer_count;
}

class ApiParam extends ffi.Struct {
  external ffi.Pointer<ffi.Char> event;

  external ffi.Pointer<ffi.Char> data;

  @ffi.UnsignedInt()
  external int data_size;

  external ffi.Pointer<ffi.Char> result;

  external ffi.Pointer<ffi.Pointer<ffi.Void>> buffer;

  external ffi.Pointer<ffi.UnsignedInt> length;

  @ffi.UnsignedInt()
  external int buffer_count;
}

class IrisCEventHandler extends ffi.Struct {
  external Func_Event OnEvent;
}

typedef Func_Event = ffi
    .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<EventParam>)>>;
typedef IrisApiRtmEnginePtr = ffi.Pointer<ffi.Void>;
typedef IrisEventHandlerHandle = ffi.Pointer<ffi.Void>;
