name: Unit test

on: push

jobs:
  run_flutter_unit_test:
    name: Run flutter unit test
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0', '3.3.9']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter packages get
      - run: flutter test